### ISSUE TITLE
Toolbar Icon Greyed Out - Cannot Access At All

### ISSUE THREAD

**Issue by 473442** [Lusito/forget-me-not#78] opened 2018-08-19 11:24 UTC
Hi, I just installed Forget Me Not, and I cannot get it to work at all. I went to my Add Ons manager in Firefox, and there's no button for options. The icon in my toolbar is greyed out, so I can't even turn the thing on or access the settings. Left click does nothing. Right click does nothing. How do I enable this add on?

**Comment by Lusito** [comment] 2018-08-19 13:48
The icon should only be grayed out when you're using private mode. Maybe you've configured Firefox to stay in private mode by default?

#15 is about adding support for private windows.

**Comment by 473442** [comment] 2018-08-19 20:33
Yeah, had it in private mode. I disabled it. Unfortunately, now I have an additional problem: I can't see all the settings. I'm not getting a scroll bar. Maybe something's blocking it. But in any case, I'm reluctant to turn off private browsing mode. At the same time, I don't trust private mode, which is why I wanted to use this app. I want to be triple and quadruple protected. I want everything blocked, but also want to click a button that gives me a warm fuzzy that everything that can be deleted has been deleted. And then I want to periodically use Bleachbit to scrub it all after the fact. Crazy right? But that's how I roll.

**Comment by Lusito** [comment] 2018-08-19 20:57
Could you make a screenshot about your settings issue? Not sure what exactly the problem is there.

Being crazy is okay. Having it "your way" is one of the main reasons this extension was started. Private Window mode will come at some point, but since there is little demand for it at this moment, I will focus my time on other issues. Feel free to give #15 a thumbs up to show your interest in this.

**Comment by Lusito** [comment] 2018-08-23 19:59
I'm gonna close this ticket, since it's a duplicate of #15. If you want to file a report for the settings bug, please open a new ticket for that. Thanks.

**Closed by Lusito** 2018-08-23 19:59 UTC
