### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by WagnerGMD** [Lusito/forget-me-not#14] opened 2017-12-14 03:50 UTC
```
lockPref("network.cookie.cookieBehavior",2);
lockPref("network.cookie.lifetimePolicy",2);
```
Hello,

to resume, I won't use the **Deny Thirdparty Cookies**. Because as you can guess, I don't need it.
Then I'm wonder if you plan to replace it ? On the page **about:preferences#privacy**, there is one button called **Exceptions...** and my idea is to create another list for them (right now, grey or blue is the choice).
Unless you believe : it wouldn't be better to create another lite addon ?

If I want to use Firefox_v58, I will need to find an alternative to [CookieKeeper](https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper/) ~~(or to wait a long time for [Cookie-AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/))~~

Kind regards.

**Comment by Lusito** [comment] 2017-12-14 15:22
I'm sorry, I can't figure out what exactly you want. Could you describe your use-case?

From your settings above, I've gathered that you deny all cookies (first line) or you only allow them until the session has ended. Not sure how they work together.
Combine that with the exceptions list and you have the behavior this extension is implementing. Not sure what other rule (list) type you want.

There will be another rule type soon (red), which can be used to override other matching rules.
In that case (#12), the user wants to whitelist all domains, except a few specific ones (for which red rules will be created).

**Comment by WagnerGMD** [comment] 2017-12-14 19:13
You're right for the first one (the deny). In my case, I'm able to create these exceptions only with CookieKeeper.

Did I miss it ? It's possible to create one exception with [Forget Me Not_v0.8.6](https://addons.mozilla.org/en-US/firefox/addon/forget_me_not/) or it will be available in the futur ?
Because I just try again today and no :
- the list is empty (according to the button **Exceptions...**)
- and I know one website doesn't work fine (in fact, it's a bad design because the CSS can't be load without cookies)

**Comment by Lusito** [comment] 2017-12-14 19:19
The extension does not have access to firefox's cookie exceptions. With Web-Extensions, it is not possible to access it, so you won't find any other extension doing that.

Everything done in the extension is combined with what you do in the firefox settings. I.e. if you tell firefox to block cookies alltogether, the extension can not work, as it will never see the cookies.
To use this extension, you need to first allow cookies in firefox and possibly remove exceptions you added.

**Comment by Lusito** [comment] 2017-12-19 01:41
I'm gonna close this as not a bug. If you think there's another issue, comment and I'll reconsider.

**Closed by Lusito** 2017-12-19 01:41 UTC

**Comment by WagnerGMD** [comment] 2017-12-22 17:51
Thank you @Lusito that's a clear answer and I wasn't aware about this Web-Extensions limitation... 
No trouble (about close) because I was absent (seek) and I had the same feeling : Firefox has to correct it. In fact, I was thinking to migrate to Firefox_v57 (Firefox Quantum) but I had change my mind. Because no Web-Extensions are missing (not ready yet).
