### ISSUE TITLE
Protecting individual Cookies

### ISSUE THREAD

**Issue by Joel889** [Lusito/forget-me-not#37] opened 2018-02-16 22:16 UTC
An expert option to drill down on a whitelisted domain's cookies and select which specific cookies to keep (as opposed to keeping all the domain's cookies) would be useful.
CookieCuller (https://addons.mozilla.org/en-US/firefox/addon/cookieculler/) and CookieKeeper (https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper/) offer that functionality, but they won't work past FF56.

Thank you

**Comment by Lusito** [comment] 2018-02-16 22:42
That's a duplicate of #17, is it not?

**Comment by Joel889** [comment] 2018-02-17 02:44
It looks like it. 

I would envision an expert mode, in which **individual** cookies are whitelisted (as opposed to whitelisting the entire domain). The reason would be to manually select cookies that store logon info or other site preferences, and delete all the other cookies from that domain. Maybe not everybody wants to manually select the cookies to keep (even though that's how CookieCuller and CookieKeeper worked), but that's why I would suggest an expert mode.

**Comment by Lusito** [comment] 2018-02-17 10:39
Yep, that's what #17 is about. Closing this one.

**Closed by Lusito** 2018-02-17 10:39 UTC
Labels: duplicate
