### ISSUE TITLE
High resource (RAM/CPU) usage in Firefox

### ISSUE THREAD

**Issue by allanlaal** [Lusito/forget-me-not#119] opened 2018-11-25 06:12 UTC
version: 1.0.5

Firefox's (Firefox Developer Edition 64.0b9) Task Manager shows Forget Me Not as its highest resource user (Energy Impact is medium to high (20..40)), which is quite a lot considering I have 160..210 tabs open
this is with the plugin not being used for days, its just showing an icon in the toolbar

**Comment by Lusito** [comment] 2018-11-25 10:41
I can't reproduce this. FMN only seems to have an actual value when I do something like closing a tab or changing a tab url. Then again, I don't have 160-210 Tabs open, so I'm nowhere near what you have.
Maybe you could share your config, so I can try better understand what feature might be doing this?

Thanks for the report.

**Comment by Lusito** [comment] 2019-01-08 11:54
Since the code has been heavily rewritten, I never could reproduce this in the first place and there is no feedback, I'm closing this for now.

**Closed by Lusito** 2019-01-08 11:54 UTC

**Comment by allanlaal** [comment] 2019-12-22 03:40
@Lusito still an issue with FMN 2.2.6 on Firefox 71.0 (build 20191202093317) on Ubuntu 16.04 LTS  with just ~220 tabs open (141 actually loaded as foreground tabs) the Resource usage was constantly over 90, hitting peaks of over 200 making Firefox slow as fuck

laptop conf:
Kernel Linux 4.10.0-42-generic x86_64
32GB RAM
64GB SSD swap
firefox running from SSD
Intel® Core™ i7-4710MQ CPU @ 2.50GHz × 8

what other data do you need?

**Comment by Lusito** [comment] 2020-01-26 16:45
I've created a new ticket, which will focus on high amounts of tabs and unloaded tabs.
