### ISSUE TITLE
'Forget' rules ignored?

### ISSUE THREAD

**Issue by tanabi** [Lusito/forget-me-not#68] opened 2018-05-30 15:13 UTC
Hey there;

You may remember me :)  I'm the guy who uses your plugin only as a black-list because I want something that logs me out of my financial sites, but I want to keep cookies everywhere else.  It seems like the "Forget" style rules are now being ignored.  My rule list looked like this (sorry for no screen shot, I couldn't screenshot + keep the plugin UI open):

\* - White
*.google.com - Forget
*.paypal.com - Forget

What to do if no rules match: White

This set of rules + default makes *everything* whitelisted.  I removed the * - White and still everything was whitelisted.

When I switch to What to do if no rules match: Forget, *everything* is forgotten (even with * - White in the rules).

So I can't figure out if its ignoring all my rules or just ignoring the forget rules ... or if the wild card is no longer being processed.  I tried deleting all my rules and re-adding them just to see if that does anything, but it did not.  There's something wrong there, though.  I've reverted to the old version (the latest 0.9x) for right now because that works for me.

Thanks! :)

**Comment by Lusito** [comment] 2018-05-30 20:48
I corrected your post, since the "* - White" was displayed as a list rather than what you intended, which confused me at first.

First of all: \* - White will catch every domain that does not fit another rule. So if the domain is not google.com or paypal.com it will always fallback to white. You are basically telling the extension to fall back to white twice.. once with the dropdown and once with the \* rule. So you can remove the * rule.

Anyway, I just tried your setup and can't seem to reproduce it..
google.com and paypal.com show a red badge and all other domains show a white (blue) badge.
I checked to see if maybe just the badge was wrong, but when I closed mozilla.org, no cookies where removed, while closing google.com removed cookies as expected.

You can create screenshots using the print key on your keyboard.

**Comment by tanabi** [comment] 2018-05-30 23:50
I don't have a print key on this keyboard unfortunately ... I think it's different on a mac.  There's some crazy key combo you can do.  Sorry my text got eaten!

That's very strange.  Well, if I ever figure out what it is, I'll let you know ... but I'll close this for now.  Thanks for taking a look.

**Comment by tanabi** [comment] 2018-05-31 02:00
Here's my settings file.  I just reinstalled the latest plugin to see if it would work.  I did clean out the dictionary with all the sites I've visited before posting this :)
[forget-me-not-settings.txt](https://github.com/Lusito/forget-me-not/files/2056330/forget-me-not-settings.txt)

**Comment by tanabi** [comment] 2018-05-31 02:01
And just for proof, the blue whitelist on google
![proof](https://user-images.githubusercontent.com/6575637/40757125-0193a144-6455-11e8-9b4c-6227a7756a9a.png)

**Comment by Lusito** [comment] 2018-05-31 10:31
I've just tried with a clean profile to load up your settings file and mail.google.com is listed as red:
![buggy-forget-me-not](https://user-images.githubusercontent.com/1135267/40777454-2da13d18-64ce-11e8-9db0-716a50e97021.png)

I'm not sure what could cause this difference in behavior.. could you try with a clean profile? Maybe another addon is interfering (tho I'm not sure how this would affect FMN).
What version of Firefox are you using?

**Comment by Lusito** [comment] 2018-09-02 15:36
I'll close this issue for now due to the lack of feedback and not being able to reproduce. Hopefully this has been solved by other bugfixes in the meantime.

**Closed by Lusito** 2018-09-02 15:36 UTC
